# Generated by Django 4.2.3 on 2023-08-18 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(max_length=4, verbose_name="性别")),
                ("year", models.CharField(max_length=4, verbose_name="出生年份")),
                ("tall", models.CharField(max_length=7, verbose_name="身高(cm)")),
                ("weight", models.CharField(max_length=7, verbose_name="体重(kg)")),
                (
                    "family",
                    models.CharField(
                        choices=[
                            ("父母有一方患有糖尿病", "父母有一方患有糖尿病"),
                            ("叔叔或者姑姑有一方患有糖尿病", "叔叔或者姑姑有一方患有糖尿病"),
                            ("无记录", "无记录"),
                        ],
                        help_text="父母有一方患有糖尿病、叔叔或者姑姑有一方患有糖尿病、无记录",
                        max_length=25,
                        verbose_name="糖尿病家族史",
                    ),
                ),
                ("press", models.CharField(max_length=7, verbose_name="舒张压(mmHg)")),
                (
                    "test",
                    models.CharField(
                        help_text="120分钟耐糖测试后的血糖值",
                        max_length=7,
                        verbose_name="口服耐糖量测试(mmol/L)",
                    ),
                ),
                (
                    "release",
                    models.CharField(
                        help_text="服糖后120分钟的血浆胰岛素水平",
                        max_length=7,
                        verbose_name="胰岛素释放实验(pmol/L)",
                    ),
                ),
                (
                    "thick",
                    models.CharField(
                        help_text="在右上臂后面肩峰与鹰嘴连线的重点处，夹取与上肢长轴平行的皮褶，纵向测量",
                        max_length=7,
                        verbose_name="肱三头肌皮褶厚度(mm)",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.datetime_safe.datetime.now,
                        verbose_name="创建日期",
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
            ],
            options={
                "verbose_name": "样本",
                "verbose_name_plural": "糖尿病数据集",
            },
        ),
    ]
