# Generated by Django 4.2.3 on 2023-08-19 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Body",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bmi",
                    models.CharField(
                        help_text="正常范围：18.5 - 24.9", max_length=7, verbose_name="体重指数"
                    ),
                ),
                (
                    "heart",
                    models.CharField(
                        help_text="正常范围：18.5 - 24.9",
                        max_length=7,
                        verbose_name="心率(次/分钟)",
                    ),
                ),
                (
                    "ssy",
                    models.CharField(
                        help_text="正常范围：小于120 mmHg",
                        max_length=7,
                        verbose_name="收缩压(mmHg)",
                    ),
                ),
                (
                    "szy",
                    models.CharField(
                        help_text="正常范围：小于80 mmHg",
                        max_length=7,
                        verbose_name="舒张压(mmHg)",
                    ),
                ),
                (
                    "bl",
                    models.CharField(
                        help_text="正常范围：小于200 mg/dL",
                        max_length=7,
                        verbose_name="总胆固醇(mg/dL)",
                    ),
                ),
                (
                    "bg",
                    models.CharField(
                        help_text="正常范围：空腹血糖小于100 mg/dL",
                        max_length=7,
                        verbose_name="血糖(mg/dL)",
                    ),
                ),
                (
                    "bone",
                    models.CharField(
                        help_text="正常范围：T值大于-1", max_length=7, verbose_name="骨密度(T值)"
                    ),
                ),
                (
                    "muscle",
                    models.CharField(
                        help_text="正常范围：男性为40-60%，女性为30-40%",
                        max_length=7,
                        verbose_name="肌肉质量(%)",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.datetime_safe.datetime.now,
                        verbose_name="创建日期",
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
            ],
            options={
                "verbose_name": "样本",
                "verbose_name_plural": "身体属性数据集",
            },
        ),
    ]
