# Generated by Django 4.2.3 on 2023-08-19 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0002_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="body",
            options={"verbose_name": "数据", "verbose_name_plural": "身体属性数据集"},
        ),
        migrations.RemoveField(
            model_name="body",
            name="applicant",
        ),
        migrations.AddField(
            model_name="body",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
    ]
