# Generated by Django 4.2.3 on 2023-08-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_body_options_remove_body_applicant_body_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="body",
            name="diary",
            field=models.TextField(blank=True, max_length=1024, verbose_name="日记"),
        ),
    ]
