# Generated by Django 4.2.3 on 2023-08-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_body_diary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="body",
            name="bg",
            field=models.FloatField(
                help_text="正常范围：空腹血糖小于100 mg/dL", max_length=7, verbose_name="血糖(mg/dL)"
            ),
        ),
        migrations.AlterField(
            model_name="body",
            name="bl",
            field=models.FloatField(
                help_text="正常范围：小于200 mg/dL", max_length=7, verbose_name="总胆固醇(mg/dL)"
            ),
        ),
        migrations.AlterField(
            model_name="body",
            name="bmi",
            field=models.FloatField(
                help_text="正常范围：18.5 - 24.9", max_length=7, verbose_name="体重指数"
            ),
        ),
        migrations.AlterField(
            model_name="body",
            name="bone",
            field=models.FloatField(
                help_text="正常范围：T值大于-1", max_length=7, verbose_name="骨密度(T值)"
            ),
        ),
        migrations.AlterField(
            model_name="body",
            name="heart",
            field=models.FloatField(
                help_text="正常范围：18.5 - 24.9", max_length=7, verbose_name="心率(次/分钟)"
            ),
        ),
        migrations.AlterField(
            model_name="body",
            name="muscle",
            field=models.FloatField(
                help_text="正常范围：男性为40-60%，女性为30-40%",
                max_length=7,
                verbose_name="肌肉质量(%)",
            ),
        ),
        migrations.AlterField(
            model_name="body",
            name="ssy",
            field=models.FloatField(
                help_text="正常范围：小于120 mmHg", max_length=7, verbose_name="收缩压(mmHg)"
            ),
        ),
        migrations.AlterField(
            model_name="body",
            name="szy",
            field=models.FloatField(
                help_text="正常范围：小于80 mmHg", max_length=7, verbose_name="舒张压(mmHg)"
            ),
        ),
    ]
